-- Skip all the user stuff until I get more of the web server and front end worked on/out
INSERT INTO users (username, password, first_name, last_name, email, is_admin)
VALUES ('testuser',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test',
        'User',
        'testuser@epicviewer.com',
        FALSE),
       ('testadmin',
        '$2b$12$AZH7virni5jlTTiGgEg4zu3lSvAw68qVEfSIOjJ3RqtbJbdW/Oi5q',
        'Test',
        'Admin!',
        'testadmin@epicviewer.com',
        TRUE);

INSERT INTO scansionPatterns (pattern)
VALUES ('DDDD'), ('DDDS'), ('DDSD'), ('DDSS'),
       ('DSDD'), ('DSDS'), ('DSSD'), ('DSSS'),
       ('SDDD'), ('SDDS'), ('SDSD'), ('SDSS'),
       ('SSDD'), ('SSDS'), ('SSSD'), ('SSSS');

INSERT INTO languages (name, lang_code)
VALUES ('Latin', 'LAT');

INSERT INTO partsOfSpeech (part)
VALUES ('noun'),
       ('verb'),
       ('adjective'),
       ('adverb'),
       ('pronoun'),
       ('preposition'),
       ('conjunction'),
       ('interjection'),
       ('determiner'),
       ('punctuation'),
       ('prefix, ETC (misc)');

INSERT INTO headwords (headword, dict_entry, part_id)
VALUES ('Aeneas', 'son of Venus and Anchises', 1),
       ('genitor', 'parent, father, sire', 1),
       ('homo', 'a human being, man, human, person', 1),
       ('deus', 'god, deity', 1),
       ('voluptas', 'pleasure, satisfaction, delight, COG.', 1),
       ('alo', 'to foster, nourish, raise, feed, maintain, develop', 2),
       ('Venus', 'the goddess of Love, the goddess Venus, love, sexual love, a beloved object, beloved, loveliness, beauty, charms, etc.', 1),
       ('caelum', 'the sky, heaven, heavens, vault of heaven', 1),
       ('labor', 'to glide, slide, move, slip, float, pass, flow', 2),
       ('signum', 'a mark, token, sign, indication, proof', 1),
       ('mare', 'the sea', 1),
       ('navis', 'a ship', 1),
       ('terra', 'the earth, land, ground, soil', 1),
       ('frux', 'produce, crop, fruit', 1),
       ('celebro', 'to frequent, throng, crowd, fill', 2),
       ('genus', 'a race, stock, family, birth, descent, origin', 1),
       ('omnis', 'all, every', 3),
       ('animus', 'that life-giving aspect which animates, life, life force, soul, vitality, COG., ETC.', 1),
       ('capio', 'to take, seize, grasp', 2),
       ('viso', 'to look at attentively, view, behold, survey', 2),
       ('orior', 'to arise, rise, stir, get up', 2),
       ('lumen', 'light', 1),
       ('sol', 'the sun', 1),
       ('fugio', 'to flee, fly, take flight, run away, make off', 2),
       ('ventus', 'wind', 1),
       ('nubes', 'a cloud, mist, vapor', 1),
       ('venio', 'to come, approach', 2),
       ('suadeo', 'to advise, recommend, exhort, urge, persuade', 2),
       ('Daedalus', 'the mythical Athenian architect of the times of Theseus and Minos, father of Icarus, and builder of the Cretan labyrinth', 1),
       ('tellus', 'the earth, globe, land, ground', 1),
       ('mitto', 'to cause to go, let go, send, send off, despatch', 2),
       ('flos', 'a blossom, flower', 1),
       ('rideo', 'to laugh, laugh at, ridicule, mock', 2),
       ('aequus', 'even, plain, flat, level', 3),
       ('pontus', 'the sea, deep', 1),
       ('placo', 'to quiet, soothe, assuage, allay, appease', 2),
       ('niteo', 'to shine, look bright, glitter, glisten', 2),
       ('fundo', 'to pour, pour out, shed', 2),
       ('tu', 'thou, you, second singular person', 5),
       ('arma', 'arms, weapons of war, weaponry, implements, outfit, instruments, tools', 1),
       ('vir', 'a male person, adult male, man', 1),
       ('cano', 'to utter melodious notes, make music, sing, sound, play', 2),
       ('Troia', 'Troy, the ancient city in Phrygia', 1),
       ('prior', 'former, prior, previous', 3),
       ('ora', 'an extremity, border, brim, edge, rim, margin, end, boundary, limit', 1),
       ('Italia', 'Italy, ETC.', 1),
       ('fatum', 'an utterance, prophetic declaration, oracle, that which is ordained, destiny, fate', 1),
       ('Lavinium', 'a city of Latium, near the sea-coast, six Roman miles distant from Laurentium, founded by Aeneas in honor of his wife Lavinia', 1),
       ('litus', 'strand, shore, beach', 1),
       ('multus', 'much, many', 3),
       ('ille', 'that, those, third person singular determiner pronoun', 5),
       ('et', 'and, in all its various forms, ETC.', 7),
       ('iacio', 'to throw, cast, fling, hurl', 2),
       ('vis', 'strength, force, vigor, power, energy, virtue, ETC.', 1),
       ('sub', 'under, beneath, below, behind', 6),
       ('super', 'over, above, upon, on', 6),
       ('saevus', 'raging, mad, furious, fell, fierce, savage, ferocious', 3),
       ('memor', 'mindful, remembering, heedful, COG.', 3),
       ('Iuno', 'the goddess Juno, daughter of Saturn, sister and wife of Jupiter, and the guardian deity of women', 1),
       ('ob', 'in the direction of, to, towards, on account of, because of, for', 6),
       ('ira', 'anger, wrath, rage, ire, passion, indignation, COG.', 1),
       ('bellum', 'war', 1),
       ('patior', 'to suffer, endure, undergo, support, bear, COG.', 2),
       ('condo', 'to put together, make by joining, found, establish, build, settle', 2),
       ('urbs', 'a city, walled town, the City, Rome', 1),
       ('fero', 'to bear, carry, support, lift, hold, take up', 2),
       ('Latium', 'the name of the mythical king, a country of Italy in which Rome was situated, now Campagna di Roma, and a part of Terra di Lavoro, consisting of two parts, ETC.', 1),
       ('Alba', 'the mother city of Rome, built by Ascanius son of Aeneas, upon the broad rocky margin lying between the Alban Lake and Mons Albanus', 1),
       ('pater', 'a father, sire', 1),
       ('moenia', 'defensive walls, ramparts, bulwarks, city walls', 1),
       ('Roma', 'Rome, the mother city, founded in the second year of the seventh Olympiad 753 BCE', 1),
       ('ab', 'departure from some fixed point, from, away from', 6),
       ('facio', 'to make, construct, fashion, frame, build, erect, produce, compose', 2),
       ('laetus', 'happy, cheerful, glad, joyful, COG.', 3),
       ('seges', 'a cornfield', 1),
       ('sidus', 'stars united in a figure, a group of stars, a constellation', 1),
       ('verto', 'to turn, revolve', 2),
       ('Maecenas', 'a Roman knight, the friend of Augustus and the patron of Horace and Vergil', 1),
       ('ulmus', 'the elm', 1),
       ('iungo', 'to join, unite togeter, connect, attach, fasten, yoke', 2),
       ('vieo', 'to bend, twist together, plait, weave', 2),
       ('cura', 'trouble, care, attention, pains, industry, diligence, exertion, COG.', 1),
       ('bos', 'an ox, bull, cow', 1),
       ('colo', 'to till, tend, care for, cultivate', 2),
       ('habeo', 'to have, hold, support, carry, wear', 2),
       ('sum', 'to be, exist, live, ETC.', 2),
       ('pecus', 'a head of cattle, beast, brute, animal, one of a herd', 1),
       ('apis', 'a bee', 1),
       ('experior', 'to try, prove, test, experience, endure, COG(?)', 2),
       ('parco', 'to act sparingly, be sparing, spare, refrain from, use moderately', 2),
       ('hic', 'this, these', 5),
       ('o', 'exclamation, indication of vocative, ETC?', 8),
       ('clarus', 'clear, bright, shining, brilliant', 3),
       ('mundus', 'clean, pure, neat, fine, nice, elegant, sophisticated, decorated, adorned', 3),
       ('pro', 'forward direction or movement, action directed forward or in front, prominence, in place of or on behalf of, ETC.', 11),
       ('aer', 'the air, atmosphere, sky, esp. the lower air', 1),
       ('mel', 'honey', 1),
       ('do', 'to give, offer, render', 2),
       ('sequor', 'to follow, come or go after, pursue', 2),
       ('specio', 'to look, look at, behold, observe, watch, COG? or just originally narrowly physical etc?', 2),
       ('pars', 'a part, portion, piece, share', 1),
       ('miror', 'to wonder, marvel, be astonished, be amazed, admire, COG.', 2),
       ('levis', 'light, not heavy', 3),
       ('res', 'a thing, object, matter, affair, business, event, fact, circumstance, occurrence, deed, condition, case, ETC.', 1),
       ('duco', 'to lead, conduct, guide, direct, draw', 2),
       ('totus', 'whole, all, entire, total, complete, every part', 3),
       ('ordo', 'a row, line, series, order, rank', 1),
       ('gens', 'a race, clan, house', 1),
       ('mos', 'a will, way, habit, manner, fashion', 1),
       ('studeo', 'to give attention, be eager, be zealous, take pains, strive after, COG.', 2),
       ('populus', 'a people, nation', 1),
       ('proelium', 'a battle, combat, conflict', 1),
       ('dico', 'to say, speak, utter, tell, mention, relate, affirm', 2),
       ('in', 'in, within, on, upon, among, at, into, to, towards, denotes either rest or motion within or into a place or thing, opp. to ex', 6),
       ('tenuis', 'drawn out, meagre, slim, thin, lank, slender', 3),
       ('labor', 'labor, toil, exertion', 1),
       ('non', 'general negation, may want to expand or reclassify later', 4),
       ('gloria', 'glory, fame, renown, praise, honor', 1),
       ('si', 'if, putting general conditional particle here', 4),
       ('numen', 'a nod of the head, divine sway or will, divine power or right, divinity', 1),
       ('laevus', 'left, on the left side, awkward, foolish, unlucky, unfortunate, bad, pernicious, unfavorable, hostile', 3),
       ('sino', 'to put, lay, set down, let, permit, allow, suffer', 2),
       ('audio', 'to hear, listen to', 2),
       ('voco', 'to call, summon, beckon, invoke', 2),
       ('Apollo', 'son of Jupiter and Latrona, twin brother of Diana, god of the sun, god of poetry and music, presiding over the Muses, ETC.', 1),
       ('qui', 'who, which, what', 5),
       ('emo', 'to buy, purchase, acquire, procure', 2),
       ('mens','the mind, disposition, feeling, character, heart, soul', 1),
       ('haurio', 'to draw, esp. water, drain', 2),
       ('aether', 'the upper air, sky, firmament', 1),
       ('eo', 'to go, walk, ride, sail, fly, move, pass', 2),
       ('per', 'through, across', 6),
       ('traho', 'to draw, drag, haul, pull, ETC?', 2);

INSERT INTO lemmae (lemma, dict_entry, headword_id, part_id)
VALUES ('Aeneadis', 'son of Aeneus, patronymic', 1, 3),
       ('genetrix', 'she who produces, a mother', 2, 1),
       ('homo', 'a human being, man, human, person', 3, 1),
       ('divus', 'a god, deity, divine being', 4, 1),
       ('voluptas', 'pleasure, satisfaction, delight', 5, 1),
       ('almus', 'nourishing, fruitfull, foodgiving', 6, 3),
       ('Venus', 'the goddess of Love, the goddess Venus', 7, 1),
       ('caelum', 'the sky, heaven, heavens, vault of heaven', 8, 1),
       ('subter', 'below, beneath, underneath', 55, 6),
       ('labor', 'to glide, slide, move, slip, float, pass, flow', 9, 2),
       ('signum', 'a mark, token, sign, indication, proof', 10, 1),
       ('qui', 'who, which, what', 126, 5),
       ('mare', 'the sea', 11, 1),
       ('naviger', 'ship-bearing, navigable', 12, 3),
       ('terra', 'the earth, land, ground, soil',13, 1),
       ('frugiferens', 'fruitbearing', 14, 3),
       ('concelebro', 'to attend in numbers, frequent, celebrate, solemnize', 15, 2),
       ('per', 'through, across, through the midst of, from side to side of, traversing', NULL, 6),
       ('tu', 'thou, you', 39, 5),
       ('quoniam', 'since now, since then, since, seeing that, as, because, whereas', NULL, 4),
       ('genus', 'a race, stock, family, birth, descent, origin', 16, 1),
       ('omnis', 'all, every', 17, 3),
       ('animo', 'to enliven, quicken, animate, ETC.', 18, 2),
       ('concipio', 'to take hold of, take up, take in, take, receive', 19, 2),
       ('viso', 'to look at attentively, view, behold, survey', 20, 2),
       ('exortus', 'a coming forth, rising', 21, 1),
       ('lumen', 'light', 22, 1),
       ('sol', 'the sun', 23, 1),
       ('dea', 'a goddess', 4, 1),
       ('fugio', 'to flee, fly, take flight, run away, make off', 24, 2),
       ('ventus', 'wind', 25, 1),
       ('nubilum', 'cloud, mist', 26, 1),
       ('adventus', 'a coming, approach, arrival', 27, 1),
       ('tuus', 'thy, thine, your, yours', 39, 3),
       ('suavis', 'sweet, agreeable, grateful', 28, 3),
       ('daedalus', 'skilful, cunning', 29, 3),
       ('tellus', 'the earth, globe, land, ground', 30, 1),
       ('summitto', 'to place underneath, put forth, rear, raise, moderate, restrain, submit', 31, 2),
       ('flos', 'a blossom, flower', 32, 1),
       ('rideo', 'to laugh, laugh at, ridicule, mock', 33, 2),
       ('aequor', 'an even surface, level', 34, 1),
       ('pontus', 'the sea, deep', 35, 1),
       ('placo', 'to quiet, soothe, assuage, allay, appease', 36, 2),
       ('niteo', 'to shine, look bright, glitter, glisten', 37, 2),
       ('diffundo', 'to spread by pouring, pour out, pour forth', 38, 2),
       ('arma', 'arms, weapons of war, weaponry, implements, outfit, instruments, tools', 40, 1),
       ('vir', 'a male person, adult male, man', 41, 1),
       ('cano', 'to utter melodious notes, make music, sing, sound, play', 42, 2),
       ('Troius', 'of Troy, Trojan', 43, 3),
       ('ab', 'departure from some fixed point, from, away from', 72, 6),
       ('ora', 'an extremity, border, brim, edge, rim, margin, end, boundary, limit', 45, 1),
       ('Italia', 'Italy, ETC.', 46, 1),
       ('fatum', 'an utterance, prophetic declaration, oracle, that which is ordained, destiny, fate', 47, 1),
       ('profugus', 'that which flees, fugitive', 24, 3),
       ('Lavinius', 'of Lavinium, the city of Latium', 48, 3),
       ('litus', 'strand, shore, beach', 49, 1),
       ('multum', 'much, very much, a lot', 50, 4),
       ('ille', 'that, those, third person singular determiner pronoun', 51, 5),
       ('et', 'and, ETC.', 52, 7),
       ('iacto', 'to throw, cast, hurl', 53, 2),
       ('altum', 'height, depth, the deep, the sea', 6, 1),
       ('vis', 'strength, force, vigor, power, energy, virtue', 54, 1),
       ('superus', 'above, upper, higher', 56, 3),
       ('saevus', 'raging, mad, furious, fell, fierce, savage, ferocious', 57, 3),
       ('memor', 'mindful, remembering, heedful', 58, 3),
       ('Iuno', 'the goddess Juno, daughter of Saturn, sister and wife of Jupiter, and the guardian deity of women', 59, 1),
       ('ob', 'in the direction of, to, towards, on account of, because of, for', 60, 6),
       ('ira', 'anger, wrath, rage, ire, passion, indignation', 61, 1),
       ('multus', 'many, a great number', 50, 3),
       ('quoque', 'also, too', NULL, 7),
       ('bellum', 'war', 62, 1),
       ('patior', 'to suffer, endure, undergo, support, bear', 63, 2),
       ('dum', 'while', NULL, 7),
       ('condo', 'to put together, make by joining, found, establish, build, settle', 64, 2),
       ('urbs', 'a city, walled town, the City, Rome', 65, 1),
       ('infero', 'to bring in, introduce, bring to, carry in', 66, 2),
       ('deus', 'a god, deity', 4, 1),
       ('Latium', 'the name of the mythical king, a country of Italy in which Rome was situated, now Campagna di Roma, and a part of Terra di Lavoro, consisting of two parts, ETC.', 67, 1),
       ('unde', 'whence, from where', NULL, 4),
       ('Latinus', 'of Latium, Latin', 67, 3),
       ('Albanus', 'pertaining to the town of Alba, Alban', 68, 3),
       ('pater', 'a father, sire', 69, 1),
       ('atque', 'and also, and besides, and even, and', 52, 7),
       ('moenia', 'defensive walls, ramparts, bulwarks, city walls', 70, 1),
       ('Roma', 'Rome, the mother city', 71, 1),
       ('primus', 'first', 44, 3),
       ('venio', 'to come, approach', 27, 2),
       ('altus', 'grown or become great, great, high, lofty, elevated', 6, 3),
       ('facio', 'to make, construct, fashion, frame, build, erect, produce, compose', 73, 2),
       ('laetus', 'happy, cheerful, glad, joyful', 74, 3),
       ('seges', 'a cornfield', 75, 1),
       ('quis', 'who, what, ETC.', NULL, 5),
       ('sidus', 'stars united in a figure, a group of stars, a constellation', 76, 1),
       ('verto', 'to turn, revolve', 77, 2),
       ('Maecenas', 'a Roman knight, the friend of Augustus and the patron of Horace and Vergil', 78, 1),
       ('ulmus', 'the elm', 79, 1),
       ('adiungo', 'to fasten on, join to, harness', 80, 2),
       ('vitis', 'a vine, grape-vine', 81, 1),
       ('convenio', 'to come together, meet, assemble, gather, come in a body', 27, 2),
       ('cura', 'trouble, care, attention, pains, industry, diligence, exertion', 82, 1),
       ('bos', 'an ox, bull, cow', 83, 1),
       ('cultus', 'labor, care, cultivation, culture', 84, 1),
       ('habeo', 'to have, hold, support, carry, wear', 85, 2),
       ('sum', 'to be, exist, live', 86, 2),
       ('pecus', 'a head of cattle, beast, brute, animal, one of a herd', 87, 1),
       ('apis', 'a bee', 88, 1),
       ('quantus', 'how much, how many', NULL, 3),
       ('experientia', 'a trial, proof, experiment', 89, 1),
       ('parcus', 'sparing, frugal, thrifty, economical, stingy, penurious, parsimonious', 90, 3),
       ('hinc', 'from this place, hence', 91, 4),
       ('incipio', 'to take hold, take in hand, begin', 19, 2),
       ('o', 'exclamation, indication of vocative', 92, 8),
       ('clarus', 'clear, bright, shining, brilliant', 93, 3),
       ('mundus', 'ornaments, decorations, dress of a woman, universe, world, calque of Greek kosmos', 94, 1),
       ('protinus', 'immediately, forthwith, continuously, constantly, uninterruptedly', 95, 4),
       ('aerius', 'of or pertaining to the air, aerial', 96, 3),
       ('mel', 'honey', 97, 1),
       ('caelestis', 'celestial, of or from the heavens, heavenly', 8, 3),
       ('donum', 'a gift, present', 98, 1),
       ('exsequor', 'to follow to the end, follow after thoroughly, go or seek after persistently', 99, 2),
       ('etiam', 'now too, yet, as yet, even yet, still, even now', 52, 7),
       ('aspicio', 'to look at or towards, behold, regard, respect, view, see', 100, 2),
       ('pars', 'a part, portion, piece, share', 101, 1),
       ('hic', 'this, these', 91, 3),
       ('admiror', 'to regard with wonder, admire', 102, 2),
       ('levis', 'light, not heavy', 103, 3),
       ('spectaculum', 'a sight, show, spectacle', 100, 1),
       ('res', 'a thing, object, matter, affair, business, event, fact, circumstance, occurrence, deed, condition, case', 104, 1),
       ('magnanimus', 'greatsouled, highminded, magnanimous', 18, 3),
       ('dux', 'a leader, conductor, guide', 105, 1),
       ('totus', 'whole, all, entire, total, complete, every part', 106, 3),
       ('ordo', 'a row, line series, order, rank', 107, 1),
       ('gens', 'a race, clan, house', 108, 1),
       ('mos', 'a will, way, habit, manner, fashion', 109, 1),
       ('studium', 'application, assiduity, zeal, eagerness, fondness, inclination, desire, exertion, endeavor, study', 110, 1),
       ('populus', 'a people, nation', 111, 1),
       ('proelium', 'a battle, combat, conflict', 112, 1),
       ('dico', 'to say, speak, utter, tell, mention, relate, affirm', 113, 2),
       ('in', ' in, within, on, upon, among, at, into, to, towards', 114, 6),
       ('tenuis', 'drawn out, meagre, slim, thin, lank, slender', 115, 3),
       ('labor', 'labor, toil, exertion', 116, 1),
       ('at', 'moreover, but, yet, adding a diff. but not entirely opp. thought, qualification, restriction, sometimes an emphasized and', 52, 7),
       ('non', 'not', 117, 4),
       ('gloria', 'glory, fame, renown, praise, honor', 118, 1),
       ('si', 'if', 119, 4),
       ('numen', 'a nod of the head, divine sway or will, divine power or right, divinity', 120, 1),
       ('laevus', 'left, on the left side, awkward, foolish, unlucky, unfortunate, bad, pernicious, unfavorable, hostile', 121, 3),
       ('sino', 'to put, lay, set down, let, permit, allow, suffer', 122, 2),
       ('audio', 'to hear, listen to', 123, 2),
       ('voco', 'to call, summon, beckon, invoke', 124, 2),
       ('Apollo', 'son of Jupiter and Latrona, twin brother of Diana, god of the sun, god of poetry and music, presiding over the Muses', 125, 1),
       ('quidam', 'a certain, certain one, somebody, one, something', 126, 5),
       ('exemplum', 'a sample, example, warning, lesson, penalty, copy or transcript', 127, 1),
       ('sequor', 'to follow, come after, follow after, attend, accompany, pursue', 99, 2),
       ('divinus', 'of a god, of a divinity, divine', 4, 3),
       ('mens', 'the mind, disposition, feeling, character, heart, soul', 128, 1),
       ('haustus', 'a drawing, draught, drink', 129, 1),
       ('aetherius', 'of the upper air, heavenly, etherial, celestial', 130, 3),
       ('namque', 'for, for indeed, since', NULL, 7),
       ('eo', 'to go, walk, ride, sail, fly, move, pass', 131, 2),
       ('per', 'through, across', 132, 6),
       ('tractus', 'a drawing, dragging, hauling, pulling, stretch, extent, tract', 133, 1),
       ('profundus', 'deep, profound, vast', 38, 3);

INSERT INTO words (word, lemma_id, lang_code, part_id)
VALUES ('Aeneadum', 1, 'LAT', 1),
       ('genetrix', 2, 'LAT', 1),
       (',', NULL, NULL, 10 ),
       ('hominum', 3, 'LAT', 1),
       ('divomque', 4, 'LAT', 1),
       ('voluptas', 5, 'LAT', 1),
       ('alma', 6, 'LAT', 3),
       ('Venus', 7, 'LAT', 1),
       ('caeli', 8, 'LAT', 1),
       ('subter', 9, 'LAT', 6),
       ('labentia', 10, 'LAT', 2),
       ('signa', 11, 'LAT', 1),
       ('quae', 12, 'LAT', 5),
       ('mare', 13, 'LAT', 1),
       ('navigerum', 14, 'LAT', 3),
       ('terras', 15, 'LAT', 1),
       ('frugiferentis', 16, 'LAT', 3),
       ('concelebras', 17, 'LAT', 2),
       ('per', 18, 'LAT', 6),
       ('te', 19, 'LAT', 5),
       ('quoniam', 20, 'LAT', 4),
       ('genus', 21, 'LAT', 1),
       ('omne', 22, 'LAT', 3),
       ('animantum', 23, 'LAT', 2),
       ('concipitur', 24, 'LAT', 2),
       ('visitque', 25, 'LAT', 2),
       ('exortum', 26, 'LAT', 1),
       ('lumina', 27, 'LAT', 1),
       ('solis', 28, 'LAT', 1),
       (':', NULL, NULL, 10),
       ('dea', 29, 'LAT', 1),
       ('fugiunt', 30, 'LAT', 2),
       ('venti', 31, 'LAT', 1),
       ('nubila', 32, 'LAT', 1),
       ('adventumque', 33, 'LAT', 1),
       ('tuum', 34, 'LAT', 3),
       ('tibi', 19, 'LAT', 3),
       ('suavis', 35, 'LAT', 3),
       ('daedala', 36, 'LAT', 3),
       ('tellus', 37, 'LAT', 1),
       ('summittit', 38, 'LAT', 2),
       ('flores', 39, 'LAT', 1),
       ('rident', 40, 'LAT', 2),
       ('aequora', 41, 'LAT', 1),
       ('ponti', 42, 'LAT', 1),
       ('placatumque', 43, 'LAT', 2),
       ('nitet', 44, 'LAT', 2),
       ('diffuso', 45, 'LAT', 2),
       ('lumine', 27, 'LAT', 1),
       ('caelum', 8, 'LAT', 1),
       ('.', NULL, NULL, 10),
       ('arma', 46, 'LAT', 1),
       ('virumque', 47, 'LAT', 1),
       ('cano', 48, 'LAT', 2),
       ('Troiae', 49, 'LAT', 3),
       ('primus', 86, 'LAT', 3),
       ('ab', 50, 'LAT', 6),
       ('oris', 51, 'LAT', 1),
       ('Italiam', 52, 'LAT', 1),
       ('fato', 53, 'LAT', 1),
       ('profugus', 54, 'LAT', 1),
       ('Laviniaque', 55, 'LAT', 3),
       ('venit', 87, 'LAT', 2),
       ('litora', 56, 'LAT', 1),
       ('multum', 57, 'LAT', 4),
       ('ille', 58, 'LAT', 5),
       ('et', 59, 'LAT', 7),
       ('terris', 15, 'LAT', 1),
       ('iactatus', 60, 'LAT', 3),
       ('alto', 61, 'LAT', 1),
       ('vi', 62, 'LAT', 1),
       ('superum', 63, 'LAT', 1),
       ('saevae', 64, 'LAT', 3),
       ('memorem', 65, 'LAT', 3),
       ('Iunonis', 66, 'LAT', 1),
       ('ob', 67, 'LAT', 6),
       ('iram', 68, 'LAT', 1),
       ('multa', 69, 'LAT', 1),
       ('quoque', 70, 'LAT', 7),
       ('bello', 71, 'LAT', 1),
       ('passus', 72, 'LAT', 2),
       ('dum', 73, 'LAT', 7),
       ('conderet', 74, 'LAT', 2),
       ('urbem', 75, 'LAT', 1),
       ('inferretque', 76, 'LAT', 2),
       ('deos', 77, 'LAT', 1),
       ('Latio', 78, 'LAT', 1),
       (';', NULL, NULL, 10),
       ('unde', 79, 'LAT', 4),
       ('Latinum', 80, 'LAT', 1),
       ('Albanique', 81, 'LAT', 3),
       ('patres', 82, 'LAT', 1),
       ('atque', 83, 'LAT', 7),
       ('altae', 88, 'LAT', 3),
       ('moenia', 84, 'LAT', 1),
       ('Romae', 85, 'LAT', 1),
       ('qui', 12, 'LAT', 5),
       ('quid', 12, 'LAT', 5),
       ('faciat', 89, 'LAT', 1),
       ('laetas', 90, 'LAT', 3),
       ('segetes', 91, 'LAT', 1),
       ('quo', 12, 'LAT', 5),
       ('sidere', 93, 'LAT', 1),
       ('terram', 15, 'LAT', 1),
       ('vertere', 94, 'LAT', 2),
       ('Maecenas', 95, 'LAT', 1),
       ('ulmisque', 96, 'LAT', 1),
       ('adiungere', 97, 'LAT', 2),
       ('vites', 98, 'LAT', 1),
       ('conveniat', 99, 'LAT', 2),
       ('cura', 100, 'LAT', 1),
       ('boum', 101, 'LAT', 1),
       ('cultus', 102, 'LAT', 1),
       ('habendo', 103, 'LAT', 2),
       ('sit', 104, 'LAT', 2),
       ('pecori', 105, 'LAT', 1),
       ('apibus', 106, 'LAT', 1),
       ('quanta', 107, 'LAT', 3),
       ('experientia', 108, 'LAT', 1),
       ('parcis', 109, 'LAT', 3),
       ('hinc', 110, 'LAT', 4),
       ('canere', 48, 'LAT', 2),
       ('incipiam', 111, 'LAT', 2),
       ('vos', 19, 'LAT', 5),
       ('o', 112, 'LAT', 8),
       ('clarissima', 113, 'LAT', 3),
       ('mundi', 114, 'LAT', 1),
       ('protinus', 115, 'LAT', 4),
       ('aerii', 116, 'LAT', 3),
       ('mellis', 117, 'LAT', 1),
       ('caelestia', 118, 'LAT', 3),
       ('dona', 119, 'LAT', 1),
       ('exsequar', 120, 'LAT', 2),
       ('hanc', 124, 'LAT', 3),
       ('etiam', 121, 'LAT', 7),
       ('aspice', 122, 'LAT', 2),
       ('partem', 123, 'LAT', 1),
       ('admiranda', 125, 'LAT', 2),
       ('levium', 126, 'LAT', 3),
       ('spectacula', 127, 'LAT', 1),
       ('rerum', 128, 'LAT', 1),
       ('magnanimosque', 129, 'LAT', 3),
       ('duces', 130, 'LAT', 1),
       ('totiusque', 131, 'LAT', 3),
       ('ordine', 132, 'LAT', 1),
       ('gentis', 133, 'LAT', 1),
       ('mores', 134, 'LAT', 1),
       ('studia', 135, 'LAT', 1),
       ('populos', 136, 'LAT', 1),
       ('proelia', 137, 'LAT', 1),
       ('dicam', 138, 'LAT', 2),
       ('in', 139, 'LAT', 6),
       ('tenui', 140, 'LAT', 3),
       ('labor', 141, 'LAT', 1),
       ('at', 142, 'LAT', 7),
       ('tenuis', 140, 'LAT', 3),
       ('non', 143, 'LAT', 4),
       ('gloria', 144, 'LAT', 1),
       ('si', 145, 'LAT', 4),
       ('quem', 92, 'LAT', 5),
       ('numina',146, 'LAT', 1),
       ('laeva', 147, 'LAT', 3),
       ('sinunt', 148, 'LAT', 2),
       ('auditque', 149, 'LAT', 2),
       ('vocatus', 150, 'LAT', 3),
       ('Apollo', 151, 'LAT', 1),
       ('his', 124, 'LAT', 5),
       ('quidam', 152, 'LAT', 5),
       ('signis', 11, 'LAT', 1),
       ('haec', 124, 'LAT', 5),
       ('exempla', 153, 'LAT', 1),
       ('secuti', 154, 'LAT', 3),
       ('esse', 104, 'LAT', 1),
       ('divinae', 155, 'LAT', 3),
       ('mentis', 156, 'LAT', 1),
       ('haustus', 157, 'LAT', 1),
       ('aetherios', 158, 'LAT', 3),
       ('dixere', 138, 'LAT', 2),
       ('deum', 77, 'LAT', 1),
       ('namque', 159, 'LAT', 7),
       ('ire', 160, 'LAT', 2),
       ('per', 161, 'LAT', 6),
       ('omnia', 22, 'LAT', 3),
       ('terrasque', 15, 'LAT', 1),
       ('tractusque', 162, 'LAT', 1),
       ('maris', 13, 'LAT', 1),
       ('caelumque', 8, 'LAT', 1),
       ('profundum', 163, 'LAT', 3);

INSERT INTO kennings (kenning)
VALUES ('Aeneadum genetrix'),
       ('hominum divomque voluptas'),
       ('alma Venus'),
       ('caeli subter labentia signa'),
       ('mare navigerum'),
       ('terras frugiferentis'),
       ('genus omne animantum'),
       ('lumina solis'),
       ('nubila caeli'),
       ('daedala tellus'),
       ('aequora ponti'),
       ('diffuso lumine'),
       ('arma virumque'),
       ('altae moenia Romae'),
       ('laetas segetes'),
       ('aerii mellis'),
       ('caelestia dona'),
       ('divinae mentis'),
       ('haustus aetherios'),
       ('tractusque maris'),
       ('caelumque profundum');

INSERT INTO authors (short_name, full_name)
VALUES ('Lucretius', 'Titus Lucretius Carus'),
       ('Vergil', 'Publius Vergilius Maro');

INSERT INTO works (short_title, full_title, author_id, lang_code)
VALUES ('De Rerum Natura', 'De Rerum Natura', 1, 'LAT'),
       ('Aeneid', 'Aeneid', 2, 'LAT'),
       ('Georgics', 'Georgicon', 2, 'LAT');

INSERT INTO lines (line_num, line_text, fifth_foot_spondee, scan_pattern_id, book_num, work_id) 
VALUES (1, 'Aeneadum genetrix, hominum divomque voluptas,', FALSE, 2, 1, 1),
       (2, 'alma Venus, caeli subter labentia signa', FALSE, 8, 1, 1),
       (3, 'quae mare navigerum, quae terras frugiferentis', FALSE, 4, 1, 1),
       (4, 'concelebras, per te quoniam genus omne animantum', FALSE, 5, 1, 1),
       (5, 'concipitur visitque exortum lumina solis:', FALSE, 8, 1, 1),
       (6, 'te, dea, te fugiunt venti, te nubila caeli', FALSE, 4, 1, 1),
       (7, 'adventumque tuum, tibi suavis daedala tellus', FALSE, 10, 1, 1),
       (8, 'summittit flores, tibi rident aequora ponti', FALSE, 14, 1, 1),
       (9, 'placatumque nitet diffuso lumine caelum.', FALSE, 12, 1, 1),
       (1, 'arma virumque cano, Troiae qui primus ab oris', FALSE, 4, 1, 2),
       (2, 'Italiam fato profugus Laviniaque venit', FALSE, 6, 1, 2),
       (3, 'litora, multum ille et terris iactatus et alto', FALSE, 8, 1, 2),
       (4, 'vi superum, saevae memorem Iunonis ob iram,', FALSE, 6, 1, 2),
       (5, 'multa quoque et bello passus, dum conderet urbem', FALSE, 8, 1, 2),
       (6, 'inferretque deos Latio; genus unde Latinum', FALSE, 9, 1, 2),
       (7, 'Albanique patres atque altae moenia Romae.', FALSE, 12, 1, 2),
       (1, 'quid faciat laetas segetes, quo sidere terram', FALSE, 6, 1, 3),
       (2, 'vertere, Maecenas, ulmisque adiungere vites', FALSE, 8, 1, 3),
       (3, 'conveniat, quae cura boum, qui cultus habendo', FALSE, 6, 1, 3),
       (4, 'sit pecori, apibus quanta experientia parcis,', FALSE, 3, 1, 3),
       (5, 'hinc canere incipiam. vos, o clarissima mundi', FALSE, 4, 1, 3),
       (1, 'protinus aerii mellis caelestia dona', FALSE, 4, 4, 3),
       (2, 'exsequar. hanc etiam, Maecenas, aspice partem.', FALSE, 4, 4, 3),
       (3, 'admiranda tibi levium spectacula rerum', FALSE, 10, 4, 3),
       (4, 'magnanimosque duces totiusque ordine gentis', FALSE, 4, 4, 3),
       (5, 'mores et studia et populos et proelia dicam.', FALSE, 10, 4, 3),
       (6, 'in tenui labor; at tenuis non gloria, si quem', FALSE, 2, 4, 3),
       (7, 'numina laeva sinunt auditque vocatus Apollo.', FALSE, 3, 4, 3),
       (219, 'his quidam signis atque haec exempla secuti', FALSE, 16, 4, 3),
       (220, 'esse apibus partem divinae mentis et haustus', FALSE, 8, 4, 3),
       (221, 'aetherios dixere; deum namque ire per omnia,', FALSE, 6, 4, 3),
       (222, 'terrasque tractusque maris caelumque profundum', FALSE, 14, 4, 3),
       (223, 'hinc pecudes, armenta, viros, genus omne ferarum,', FALSE, 5, 4, 3),
       (224, 'quemque sibi tenuis nascentem arcessere vitas;', FALSE, 4, 4, 3);

INSERT INTO linesWords (line_id, word_id, line_position)
VALUES (1, 1, 1),
       (1, 2, 2),
       (1, 3, 3),
       (1, 4, 4),
       (1, 5, 5),
       (1, 6, 6),
       (1, 3, 7),
       (2, 7, 1),
       (2, 8, 2),
       (2, 3, 3),
       (2, 9, 4),
       (2, 10, 5),
       (2, 11, 6),
       (2, 12, 7),
       (3, 13, 1),
       (3, 14, 2),
       (3, 15, 3),
       (3, 3, 4),
       (3, 13, 5),
       (3, 16, 6),
       (3, 17, 7),
       (4, 18, 1),
       (4, 3, 2),
       (4, 19, 3),
       (4, 20, 4),
       (4, 21, 5),
       (4, 22, 6),
       (4, 23, 7),
       (4, 24, 8),
       (5, 25, 1),
       (5, 26, 2),
       (5, 27, 3),
       (5, 28, 4),
       (5, 29, 5),
       (5, 30, 6),
       (6, 20, 1),
       (6, 3, 2),
       (6, 31, 3),
       (6, 3, 4),
       (6, 20, 5),
       (6, 32, 6),
       (6, 33, 7),
       (6, 3, 8),
       (6, 20, 9),
       (6, 34, 10),
       (6, 9, 11),
       (7, 35, 1),
       (7, 36, 2),
       (7, 3, 3),
       (7, 37, 4),
       (7, 38, 5),
       (7, 39, 6),
       (7, 40, 7),
       (8, 41, 1),
       (8, 42, 2),
       (8, 3, 3),
       (8, 37, 4),
       (8, 43, 5),
       (8, 44, 6),
       (8, 45, 7),
       (9, 46, 1),
       (9, 47, 2),
       (9, 48, 3),
       (9, 49, 4),
       (9, 50, 5),
       (9, 51, 6),
       (10, 52, 1),
       (10, 53, 2),
       (10, 54, 3),
       (10, 3, 4),
       (10, 55, 5),
       (10, 97, 6),
       (10, 56, 7),
       (10, 57, 8),
       (10, 58, 9),
       (11, 59, 1),
       (11, 60, 2),
       (11, 61, 3),
       (11, 62, 4),
       (11, 63, 5),
       (12, 64, 1),
       (12, 3, 2),
       (12, 65, 3),
       (12, 66, 4),
       (12, 67, 5),
       (12, 68, 6),
       (12, 69, 7),
       (12, 67, 8),
       (12, 70, 9),
       (13, 71, 1),
       (13, 72, 2),
       (13, 3, 3),
       (13, 73, 4),
       (13, 74, 5),
       (13, 75, 6),
       (13, 76, 7),
       (13, 77, 8),
       (14, 78, 1),
       (14, 79, 2),
       (14, 67, 3),
       (14, 80, 4),
       (14, 81, 5),
       (14, 3, 6),
       (14, 82, 7),
       (14, 83, 8),
       (14, 84, 9),
       (15, 85, 1),
       (15, 86, 2),
       (15, 87, 3),
       (15, 88, 4),
       (15, 22, 5),
       (15, 89, 6),
       (15, 90, 7),
       (16, 91, 1),
       (16, 92, 2),
       (16, 93, 3),
       (16, 94, 4),
       (16, 95, 5),
       (16, 96, 6),
       (17, 98, 1),
       (17, 99, 2),
       (17, 100, 3),
       (17, 101, 4),
       (17, 3, 5),
       (17, 102, 6),
       (17, 103, 7),
       (17, 104, 8),
       (18, 105, 1),
       (18, 3, 2),
       (18, 106, 3),
       (18, 3, 4),
       (18, 107, 5),
       (18, 108, 6),
       (18, 109, 7),
       (19, 110, 1),
       (19, 3, 2),
       (19, 13, 3),
       (19, 111, 4),
       (19, 112, 5),
       (19, 3, 6),
       (19, 97, 7),
       (19, 113, 8),
       (19, 114, 9),
       (20, 115, 1),
       (20, 116, 2),
       (20, 3, 3),
       (20, 117, 4),
       (20, 118, 5),
       (20, 119, 6),
       (20, 120, 7),
       (20, 3, 8),
       (21, 121, 1),
       (21, 122, 2),
       (21, 123, 3),
       (21, 51, 4),
       (21, 124, 5),
       (21, 3, 6),
       (21, 125, 7),
       (21, 126, 8),
       (21, 127, 9),
       (22, 128, 1),
       (22, 129, 2),
       (22, 130, 3),
       (22, 131, 4),
       (22, 132, 5),
       (23, 133, 1),
       (23, 51, 2),
       (23, 134, 3),
       (23, 135, 4),
       (23, 3, 5),
       (23, 106, 6),
       (23, 3, 7),
       (23, 136, 8),
       (23, 137, 9),
       (23, 51, 10),
       (24, 138, 1),
       (24, 37, 2),
       (24, 139, 3),
       (24, 140, 4),
       (24, 141, 5),
       (25, 142, 1),
       (25, 143, 2),
       (25, 144, 3),
       (25, 145, 4),
       (25, 146, 5),
       (26, 147, 1),
       (26, 67, 2),
       (26, 148, 3),
       (26, 67, 4),
       (26, 149, 5),
       (26, 67, 6),
       (26, 150, 7),
       (26, 151, 8),
       (26, 51, 9),
       (27, 152, 1),
       (27, 153, 2),
       (27, 154, 3),
       (27, 88, 4),
       (27, 155, 5),
       (27, 156, 6),
       (27, 157, 7),
       (27, 158, 8),
       (27, 3, 9),
       (27, 159, 10),
       (27, 160, 11),
       (28, 161, 1),
       (28, 162, 2),
       (28, 163, 3),
       (28, 164, 4),
       (28, 165, 5),
       (28, 166, 6),
       (28, 51, 7),
       (29, 167, 1),
       (29, 168, 2),
       (29, 169, 3),
       (29, 93, 4),
       (29, 170, 5),
       (29, 171, 6),
       (29, 172, 7),
       (30, 173, 1),
       (30, 117, 2),
       (30, 137, 3),
       (30, 174, 4),
       (30, 175, 5),
       (30, 67, 6),
       (30, 176, 7),
       (31, 177, 1),
       (31, 178, 2),
       (31, 88, 3),
       (31, 179, 4),
       (31, 180, 5),
       (31, 181, 6),
       (31, 182, 7),
       (31, 183, 8),
       (31, 3, 9),
       (32, 184, 1),
       (32, 185, 2),
       (32, 186, 3),
       (32, 187, 4),
       (32, 188, 5),
       (32, 88, 6);

INSERT INTO kenningsWords (kenning_id, word_id, kenning_position)
VALUES (1, 1, 1),
       (1, 2, 2),
       (2, 4, 1),
       (2, 5, 2),
       (2, 6, 3),
       (3, 7, 1),
       (3, 8, 2),
       (4, 9, 1),
       (4, 10, 2),
       (4, 11, 3),
       (4, 12, 4),
       (5, 14, 1),
       (5, 15, 2),
       (6, 16, 1),
       (6, 17, 2),
       (7, 22, 1),
       (7, 23, 2),
       (7, 24, 3),
       (8, 28, 1),
       (8, 29, 2),
       (9, 34, 1),
       (9, 9, 2),
       (10, 39, 1),
       (10, 40, 2),
       (11, 44, 1),
       (11, 45, 2),
       (12, 48, 1),
       (12, 49, 2),
       (13, 52, 1),
       (13, 53, 2),
       (14, 94, 1),
       (14, 95, 2),
       (14, 96, 3),
       (15, 100, 1),
       (15, 101, 2),
       (16, 129, 1),
       (16, 130, 2),
       (17, 131, 1),
       (17, 132, 2),
       (18, 174, 1),
       (18, 175, 2),
       (19, 176, 1),
       (19, 177, 2),
       (20, 185, 1),
       (20, 186, 2),
       (21, 187, 1),
       (21, 188, 2);







-- SPACE BELOW TO SAVE SEARCH QUERIES:

-- SELECT a.short_name, w.short_title, b.roman_num, wd.word, sp.part FROM authors AS a JOIN works AS w ON a.id = w.author_id JOIN books AS b ON w.id = b.work_id JOIN lines AS l ON b.id = l.book_id JOIN linesWords AS lw ON l.id = lw.line_id JOIN words AS wd ON lw.word_id = wd.id JOIN partsofspeech as sp ON wd.part_id = sp.id WHERE sp.id = 1;

-- SELECT k.kenning FROM kennings AS k;

-- SELECT k.kenning, l.line_text, l.line_num, l.book_rom_num, wk.short_title, a.short_name FROM kennings AS k JOIN kenningswords AS kw ON k.id = kw.kenning_id
-- JOIN words AS wd ON kw.word_id = wd.id
-- JOIN lineswords AS lw ON wd.id = lw.word_id
-- JOIN lines AS l ON lw.line_id = l.id
-- JOIN works AS wk ON l.work_id = wk.id
-- JOIN authors AS a ON wk.author_id = a.id
-- WHERE k.id = 5